littlelemon/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('restaurant/',include('restaurant.urls')),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.authtoken'))
]

restaurant/urls.py
from django.urls import path 
from .import views 
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token


app_name ='restaurant'

urlpatterns = [
    path('',views.index,name='index'),
    path('api/bookings/',views.BookingView.as_view()),
    path('api/menu/', views.MenuItemsView.as_view()),
    path('api/menu/<int:pk>', views.MenuRetrieveDestroyAPIView.as_view()),
    path('api/message/', views.msg),
    path('api-token-auth/', obtain_auth_token)
]

restaurant/models.py
from django.db import models

# Create your models here.
class Booking(models.Model):
    name = models.CharField( max_length=200)
    no_of_guests = models.IntegerField()
    booking_date =models.DateTimeField( auto_now_add=True)
    
    def __str__(self):
        return self.name
    
    
class Menu(models.Model):
    title = models.CharField( max_length=200)
    price = models.DecimalField( max_digits=5, decimal_places=2)
    inventory = models.IntegerField()
    
    def get_item(self):
        return f'{self.title} : {str(self.price)}'
    
    def __str__(self):
        return self.title
    

restaurant/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.response import Response 
from .models import Booking,Menu
from .serializers import BookingSerializer,MenuSerializer
from rest_framework.decorators import api_view
from rest_framework import generics

from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated

# Create your views here.
@api_view()
@permission_classes([IsAuthenticated])
# @authentication_classes([TokenAuthentication])
def msg(request):
    return Response({"message":"This view is protected"})



def index(request):
    return render(request,'index.html',{})

class BookingView(APIView):
    def get(self,request):
        items = Booking.objects.all()
        serializer = BookingSerializer(items,many=True)
        return Response(serializer.data)
    
    
class MenuItemsView(generics.ListCreateAPIView):
    permission_classes = [IsAuthenticated]
    queryset =Menu.objects.all()
    serializer_class = MenuSerializer

class MenuRetrieveDestroyAPIView(generics.RetrieveUpdateAPIView,generics.DestroyAPIView ):
    queryset = Menu.objects.all()
    serializer_class = MenuSerializer

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title>Little Lemon</title>
    <meta name="description" content="A brief description" />
    <meta
      name="author"
      content="Based in Chicago, Illinois, Little Lemon is a family owned Mediterranean restaurant, focused on traditional recipes served with a modern twist."
    />

    <!-- Load favicon -->
    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'img/favicon.ico' %}"
    />

    <!-- Include your CSS files here -->
    <link
      rel="preload"
      as="style"
      href="{% static 'css/style.css' %}"
      onload="this.rel = 'stylesheet'"
    />

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Karla&family=Markazi+Text:wght@500&display=swap"
      rel="stylesheet"
    />
  </head>
<header>
  <img src="{% static 'img/logo.png' %}" />
    </header>
    <nav>
      <ul>
        <li><a href="{% url 'restaurant:index' %}">Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Menu</a></li>
        <li><a href="#">Book</a></li>
      </ul>
  </nav>
<body>
<section>
    <article id="hero">
      <h1 class="heading_shadow">SPECIAL OFFER</h1>
      <p>
        30% Off This Weekend 
      </p>
      <a href="#" class="cta"> Book now </a>
    </article>
  </section>
  <section>
    <article>
      <h2>Our New Menu</h2>
      <img src="{% static 'restaurant/img/grill.jpg' %}">
      <p>
        Our menu consists of 12-15 seasonal items based on Italian, Greek, and Turkish culture.
      </p>
      <p>
        <a href="#">See our new menu</a>
      </p>
    </article>
    <article>
      <h2>Book a table</h2>
      <img src="{% static 'img/salad.jpg' %}">
      <p>
        Reserve your table for an Italian, Greek, and Turkish dining experience.
      </p>
      <p>
        <a href="#">Book your table now</a>
      </p>
    </article>
    <article>
      <h2>Opening Hours</h2>
      <img src="{% static 'img/head_chef.jpg' %}">
      <p>
        The Little Lemon Restaurant is open 7 days a week, except for public holidays. 
      </p>
      <ul>
        <li>Mon - Fri: 2pm - 10pm</li>
        <li>Sat: 2pm - 11pm</li>
        <li>Sun: 2pm - 9pm</li>
      </ul>
    </article>
  </section>
  <footer>
    <article>
      <img src="{% static 'img/logo_footer.png' %}" />
    </article>
    <article>
      <p>Copyright {{ current_year }} Little Lemon</p>
    </article>
  </footer>
</body>
</html>